modern_warehouse:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('ACCOUNT') }}"  
      database: "{{ env_var('DEV_DATABASE') }}" 
      schema: "{{ env_var('SCHEMA') }}"
      password: "{{ env_var('PASSWORD') }}"
      role: "{{ env_var('ROLE') }}"
      threads: 1
      user: "{{ env_var('USER') }}"
      warehouse: "{{ env_var('WAREHOUSE') }}"

    prod: 
      type: snowflake
      account: "{{ env_var('ACCOUNT') }}"  
      database: "{{ env_var('PROD_DATABASE') }}" 
      password: "{{ env_var('PASSWORD') }}"
      schema: "{{ env_var('SCHEMA') }}"
      role: "{{ env_var('ROLE') }}"
      threads: 1
      user: "{{ env_var('USER') }}"
      warehouse: "{{ env_var('WAREHOUSE') }}"

