version: "3"

services:
  run:
    container_name: fake_data
    build:
      context: .
    volumes:
      - ./:/code
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    command: python data/main_pipeline.py

  ci: 
    container_name: app
    build: 
      context: .
    volumes: 
      - ./:/code
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   POSTGRES_HOST: ${POSTGRES_HOST}
    #   POSTGRES_PORT: ${POSTGRES_PORT}

  

